### ISSUE TITLE
CSS 基础

### ISSUE THREAD

**Issue by jecyu** [Jecyu/Jecyu.github.io#13]
### 绘制三角形

1. 向上的三角形

```scss
.top {
    width: 0;
    height: 0;
    border-width: 10px;
    border-color: transparent;
    border-bottom-color: blue;
    border-style: solid;
}
```

2. 向下的三角形

```scss
.bottom {
    width: 0;
    height: 0;
    border-width: 10px;
    border-color: transparent;
    border-top-color: blue;
    border-style: solid;
}
```

3. 向左的三角形
```scss
.left {
    width: 0;
    height: 0;
    border-width: 10px;
    border-color: transparent;
    border-left-color: blue;
    border-style: solid;
}
```

4. 向右的三角形
```scss
.right {
    width: 0;
    height: 0;
    border-width: 10px;
    border-color: transparent;
    border-right-color: blue;
    border-style: solid;
}
```

### 一行文本溢出

```scss
@mixin oneline {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

### 多行文本溢出

```scss
@mixin line-clamp($line: 2) {
  display: -webkit-box;
  word-break: break-all;
  text-overflow: ellispis;
  -webkit-line-clamp: $line;
  -webkit-box-orient: vertical;
}
```

### 关键帧动画（Keyframes）

我们可以通过 CSS 提供的 `@keyframes` 规则整合多个简单的动画。

它会指定某个动画的名称以及相应的规则：哪个属性，何时以及何地渲染动画。

然后使用 `animation` 属性把动画绑定到相应的元素上，并为其添加额外的参数。

```html
<div class="progress"></div>

<style>
  @keyframes go-left-right {        /* 指定一个名字："go-left-right" */
    from { left: 0px; }             /* 从 left: 0px 开始 */
    to { left: calc(100% - 50px); } /* 移动至 left: 100%-50px */
  }

  .progress {
    animation: go-left-right 3s infinite alternate;
    /* 把动画 "go-left-right" 应用到元素上
       持续 3 秒
       持续次数：infinite
       每次都改变方向
    */

    position: relative;
    border: 2px solid green;
    width: 50px;
    height: 20px;
    background: lime;
  }
</style>
```

#### 圆环 loading

1. 使用 loading 图片
```scss
&-icon { 
  width: 40px;
  height: 40px;
  animation: rotating .6s linear infinite;
  @keyframes rotating {
    0% {
      transform: rotateZ(0);
    }
    100% {
      transform: rotateZ(360deg);
    }
  }
}
```

2. 使用原生 css 绘制圆环 loading

```scss
@mixin loading($color: red, $marginRight: 4px) {
  pointer-events: none;
  opacity: .8;
  &::before {
    content: '';
    display: inline-block;
    position: relative;
    width: 26px;
    height: 26px;
    box-sizing: border-box;
    border: 2px solid transparent;
    border-top-color: $color;
    border-right-color: $color;
    border-radius: 100%;
    animation: turn-around 1s linear infinite;
    @keyframes turn-around {
      0% {
        transform: rotateZ(0);
      }
      100% {
        transform: rotateZ(360deg);
      }
    }
  }
}

.container {
  @include loading;  
}
```

html 结构
```html
<div class="container">
  <span class="text">正在加载中...</span>
</div>
```
